Add some interface functions to support the new Gibbs sampler in Turing
TuringLang/AbstractMCMC.jl pull request #144
Opened 2024-07-12 15:43 UTC by sunxd3

The recent [new Gibbs sampler](https://github.com/TuringLang/Turing.jl/pull/2231) provides a way forward for the Turing inference stack. 

A near-to-medium-range goal has been to further reduce the glue code between Turing and inference packages (ref https://github.com/TuringLang/Turing.jl/issues/2281). The new Gibbs implementation laid a great plan to achieve this goal.

This PR is modeled after the interface of @torfjelde's [recent PR](https://github.com/TuringLang/Turing.jl/blob/torfjelde/gibbs-new-improv/src/mcmc/abstractmcmc.jl). And in some aspects, it is a rehash of https://github.com/TuringLang/AbstractMCMC.jl/pull/86. 

(the explanation here is outdated, please refer to https://github.com/TuringLang/AbstractMCMC.jl/pull/144#issuecomment-2337681868)

~~The goal of this PR is to determine and implement some **necessary** interface improvements, so that, when we update the inference packages up to the interface, they will more or less "just work" with the new Gibbs implementation.~~

~~As a first step, we test-flight two new functions `recompute_logprob!!(rng, model, sampler, state)` and `getparams(state)`:~~
- ~~`recompute_logprob!!(rng, model, sampler, state)` recomputes the logprob given the `state`~~
- ~~`getparams(state)` extract the parameter values~~

~~Some considerations:~~
- ~~This assumes a `state` is implemented with `AbstractMCMC` compatible inference packages. And a `state` at least stores values of parameters from the current iteration (traditionally, this is in the form of a `Transition`) and logprob.~~
- ~~`recompute_logprob!!(rng, model, sampler, state)`~~
    - ~~do we need `rng`?~~
    - ~~should we make `model` into `AbstractMCMC.LogDensityModel` or just `LogDensityProblem` (and make inference packages depend on `LogDensityProblems` in the latter case)? This should allow inference packages to be independent from DynamicPPL, we can use `getparams` to construct a `varinfo` in Turing~~
- ~~`getparams(state)` ~~
    - ~~What does this function return? A vector, a `transition`?~~
    - ~~Do we need `setparams`?~~
- ~~Do we also need some interface functions for `state` like `getstats`?~~

~~Tor also says (in a Slack conversation) that the a `condition(model, params)` is needed, but better to be implemented by packages that defines the `model`, which I agree.~~

2024-07-14 21:23 UTC, devmotion commented
How is #86 related to this PR?

2024-07-15 07:00 UTC, torfjelde commented
Hmm, it's unclear to me whether it's worth adding these methods when they have "no use" unless some notion of conditioning is also added 😕 

> How is https://github.com/TuringLang/AbstractMCMC.jl/pull/86 related to this PR?

`getparams` is probably overlapping between the two PRs, but the `recompute_logprob!!` method is not

2024-07-19 19:24 UTC, torfjelde commented on src/AbstractMCMC.jl
> +`observations` can be of any supported internal trace type, or a fixed probability expression.
There's no notion of "trace type" in AbstractMCMC

2024-07-19 19:24 UTC, torfjelde commented on src/AbstractMCMC.jl
> +function getparams(state) end
Do we say anything about what the form of these parameters should be?

2024-07-19 19:27 UTC, torfjelde commented
I'm still a bit uncertain about all of this tbh. I feel like right now we're just shoving `condition` and `decondition` (which I don't think we need for Gibbs?) into AbstractMCMC.jl to motivate the inclusion of `recompute_logprob!!` 😅 

I think if this is the case, then I'm preferential to ignoring my original comment of "needing `condition` to motivate `recompute_logprob!!`", i.e. just leave it as you did originally (without `condition` and `decondition`).

2024-07-22 08:58 UTC, torfjelde commented
> I also think we should add something like AbstractState to normalize the design of state. This will introduce types for state everywhere, I am unsure of the impact. What's your thoughts on this?

Not for this PR at least:) If we want to discuss this, then we should open an issue and move discussion there.

2024-07-22 08:59 UTC, torfjelde commented
> The latter will technically change the interface, so I bumped the minor version.

It seems you've bumped the _major_ version, not the minor version?

Also, if we're making this part of the interface, we should probably document this?

2024-09-18 11:16 UTC, torfjelde commented on docs/src/gibbs.md
> +    args...;
```suggestion
```
IIRC `args...` should not be there?

2024-09-18 11:17 UTC, torfjelde commented on docs/src/gibbs.md
> +end
```suggestion
struct Gibbs{D} <: AbstractMCMC.AbstractSampler
    sampler_map::D
end
```

2024-09-18 11:18 UTC, torfjelde commented on docs/src/gibbs.md
> +end
```suggestion
struct GibbsTransition{NT<:NamedTuple}
    values::NT
end
```

2024-09-18 11:19 UTC, torfjelde commented on docs/src/gibbs.md
> +    vi::NamedTuple
I saw the comment about calling this `trace` instead, but why not just call this `realization` or `values`?

2024-09-18 11:21 UTC, torfjelde commented on docs/src/gibbs.md
> +These are the functions that was used in the `recompute_logprob!!` function above.
This isn't quite true, no? Only two of them are actually used.

2024-09-18 11:23 UTC, torfjelde commented on docs/src/gibbs.md
> +A recomputation function could use the `state` interface to return a new state with the updated log probability.
Might be useful to add a comment on why this is useful, e.g. "later we will see how this functionality is useful if we want to implemented higher-order samplers such as Gibbs sampling"

2024-09-18 11:24 UTC, torfjelde commented on src/gibbs.jl
> +end
```suggestion
struct Gibbs{NT} <: AbstractMCMC.AbstractSampler
    sampler_map::NT
end
```

`parameter_names` seems wholly unnecessary here?

2024-09-18 11:25 UTC, torfjelde commented on src/gibbs.jl
> +struct GibbsState
What's the reason for not making this typed?

2024-09-18 11:25 UTC, torfjelde commented on src/gibbs.jl
> +struct GibbsTransition
Same here

2024-09-18 11:27 UTC, torfjelde commented on src/gibbs.jl
> +        )
Would generally recommend against this sort of "nesting" functions in arguments; it makes things less readable than if you just added a few lines above constructing the arguments.

2024-09-18 11:28 UTC, torfjelde commented on src/gibbs.jl
> +    initial_params::NamedTuple,
This does break with what we're generally suggesting in other AbstractMCMC.jl places, no? AFAIK we're generally assuming / suggesting that `initial_params` should be `AbstractVector`

2024-09-18 11:28 UTC, torfjelde commented on src/gibbs.jl
> +    initial_params::NamedTuple,
Maybe worth adding a handler which can do either `NamedTuple` or `AbstractVector`

2024-09-18 11:29 UTC, torfjelde commented on src/gibbs.jl
> +        variable_sizes[parameter_variable] = Tuple(size(initial_params[parameter_variable]))
```suggestion
        variable_sizes[parameter_variable] = size(initial_params[parameter_variable])
```
`Tuple` should really not be necessary here?

2024-09-18 11:30 UTC, torfjelde commented on src/gibbs.jl
> +        )
As as above, much prefer the following

```suggestion
        sub_model = AbstractMCMC.LogDensityModel(
            AbstractMCMC.condition(
                logdensity_model.logdensity, conditioning_variables_values
            ),
        )
        sub_state = last(
            AbstractMCMC.step(
                rng,
                sub_model,
                sub_sampler,
                args...;
                initial_params=flattened_sub_problem_parameters_values,
                kwargs...,
            ),
        )
```

2024-09-18 11:31 UTC, torfjelde commented on src/gibbs.jl
> +    mcmc_states_dict = Dict(
Is the usage of `Dict` here intentional?

2024-09-18 12:54 UTC, torfjelde commented
> I'd encourage @torfjelde and @sunxd3 to have more discussions to converge on a sensible Gibbs design; we will never get a good implementation if we don't start working on it.

Definitively! But I think it's also partially a thing that we need to try out a bit, and we're not going to get it right on the first try, hence my reluctance to putting an impl in AbstractMCMC.jl as soon as we enable the functionality.

2024-10-03 12:30 UTC, sunxd3 commented
the test error seems to be Julia 1.6-only related

2024-10-03 15:50 UTC, sunxd3 commented
related reply from @devmotion https://github.com/TuringLang/Turing.jl/pull/2304#issuecomment-2291097709

2024-10-04 10:04 UTC, torfjelde requested changes
I'm very much in favour of using explicit functions for the interface and not overloading methods (in ways that the original methods were not intended for) :confused:

2024-10-04 10:21 UTC, torfjelde commented
I do think the entire process of this would be quite a bit less painful if we did the following (I believe I've mentioned this before; if not, I apologize):
1. Improve #86 to a finalized form . This is useful, not just for Gibbs sampling.
2. Make a separate package, e.g. `AbstractMCMCGibbs.jl`, which implements the Gibbs-only stuff, e.g. `recompute_logprob!!` and the sampler mapping stuff.

This is how we're doing it with MCMCTempering.jl, i.e. keep it as a separate package and slowly move pieces to AbstractMCMC.jl if it seems suitable. My problem, as stated before, is that the current Gibbs impls we're working with are really not good enough as I think is evident by a) issues that we've encountered with my Turing.jl-impl in https://github.com/TuringLang/Turing.jl/pull/2328#issuecomment-2378971734, and b) the amount of iterating you've done in this PR. This shit is complicated :grimacing: And I imagine it's really annoying iterating on this back and forth but without actually getting stuff merged.. 

So, I think a separate package would just make this entire process much easier @sunxd3 ; then we can iterate much faster on ideas (just make breaking releases), and then we can just upstream changes as we finalize things there.

2024-10-04 10:26 UTC, sunxd3 commented on design_notes/on_gibbs_implementation.md
> +For `getparams`, we can use `Base.vec`. It is a `Base` function, so there's no need to export anything from `AbstractMCMC`. Since `getparams` should return a vector, using `vec` makes sense. The conc
I can resonate, issue with `public` is they still count as public interface, unsure if we need to make minor release

2024-10-04 10:26 UTC, sunxd3 commented on design_notes/on_gibbs_implementation.md
> +While overloading `LogDensityProblems.logdensity` to take a state object instead of a vector for the second argument somewhat deviates from the interface in `LogDensityProblems`, it provides a clean
mainly to not make any changes to the interface, so these are just "recommendations"

I think `AbstractMCMC` depends on `LogDensityProblems`

2024-10-04 15:06 UTC, torfjelde commented
https://github.com/TuringLang/AbstractMCMC.jl/issues/85#issuecomment-2061300622

2024-10-15 12:49 UTC, closed without merging