Add  `getparameters` and `setparameters!!`
TuringLang/AbstractMCMC.jl pull request #86
Opened 2021-10-21 20:57 UTC by torfjelde

See #85.

Currently, almost every package implementing a `AbstractSampler` comes with their custom state and transition types. Since there currently are no "interface" or "guidelines" about what the types of `state` and `transition` should implement, it means that interaction across different samplers, e.g. composing two samplers from different packages, is annoying.

This PR introduces some methods which aims to alleviate this issue. In particular it sampler-implementations to also implement
- `parameters(transition)` for the transition-type which returns the parameters in the sample, where by "parameters" I mean the realizations of the random variables we're targeting present in the `transition`, and
- `setparameters!!` for the state-type which updates the current state of the Markov chain, thus likely (this might depend on the sampler) conditioning the sampler/kernel on the provided parameters.

*Why `parameters` for `transition` but `setparameters!!` for `state`?* A `transition` should (AFAIK) always contain a realization of the random variables we're sampling while the `state` might not, e.g. MH with a `MvNormal(zeros(n), I)` as proposal distribution (not dependent on current position/state/parameters). Of course there might be more properties one would like to use when converting from `PackageA.Transition` to `PackageB.State`, but this seems like the lowest common denominator that we can come up with. Maaaybe we should have the same for `logdensity`, i.e. `logdensity(transition)` and `setlogdensity!!(state)`, but this might not always be available nor correspond directly to the same thing for both samplers. Might be worth including though. They could also obviously be implemented for _both_ if the implementer so chooses.

*But* for the cases where you want to make use of more than just the parameters (and potentially logdensity), one can overload the `state_from_transition` directly (which is what should be used by packages making these "meta-samplers", e.g. composition), e.g. `AdvancedHMC` might want to implement `state_from_transition(::AdvancedHMC.HMCState, ::AdvancedHMC.Transition)` to not only update the parameters in the `state` but the entire `PhasePoint` from `AdvnacedHMC.Transition`, etc.

Thoughts?

2021-11-03 13:16 UTC, torfjelde commented on src/AbstractMCMC.jl
> +    state_from_transiton(state, transition_prev[, state_prev])
Yo, whadda yah guys think?

2021-11-03 18:28 UTC, cpfiffer commented on src/AbstractMCMC.jl
> +    state_from_transiton(state, transition_prev[, state_prev])
Oh, sorry, my bad. Yeah your proposed name change is clearer, let's do that.

2021-11-04 13:38 UTC, torfjelde commented on src/AbstractMCMC.jl
> +    state_from_transiton(state, transition_prev[, state_prev])
Or maybe just `update!!`? Given that we might also want to pass in `state_prev`?

2021-11-04 13:42 UTC, devmotion commented on src/AbstractMCMC.jl
> +    state_from_transiton(state, transition_prev[, state_prev])
Yeah, since we don't want to export any of these functions anyway I'm fine with `update!!`. Is a bit nicer than `update_from_transition!!` IMO, and as you say we might not only update based on the transition.

2021-11-04 16:13 UTC, torfjelde commented on src/AbstractMCMC.jl
> +    state_from_transiton(state, transition_prev[, state_prev])
Cool, I'll make that change then :+1:

2021-11-04 16:15 UTC, torfjelde commented
Do you have ideas for alternatives to the use of `parameters` @devmotion and @cpfiffer ? As I said in my previous comment, I think "samples" is kind of confusing too. Really what we want is "set the realizations of the random variables" but I think "realizations" is too unfamiliar for people.

I think I'm leaning towards `values` and `setvalues!!`.

2021-11-04 17:55 UTC, cpfiffer commented
I dunno I feel like I wouldn't mind using `realize` or `realize!!`. Short and sweet, and I don't think it's _that_ out of the way. If that doesn't seem right, I don't mind using `values` (though I will note that it's a base function override, which I don't care about overmuch).

2021-11-17 12:44 UTC, torfjelde commented
I've added some docs + motivating example: https://turinglang.github.io/AbstractMCMC.jl/previews/PR86/api/#Interacting-with-states-of-samplers

(Btw, I love the fact that I can preview docs in the PRs; I'm guessing this is your doing @devmotion ? :heart: )

2021-11-17 15:37 UTC, cpfiffer approved these changes
Mhm yep I love it. Could you move us up a major version?

2021-11-18 02:05 UTC, torfjelde commented
I think the only thing that's left is the discussion of `parameters` vs. `realizations` vs. `values`

2021-11-18 16:47 UTC, cpfiffer commented
I prefer `realizations` but `values` is more Julian -- let's go with that.

2021-11-19 02:03 UTC, torfjelde commented
On additional thing we might want to consider adding: `logdensity` and `setlogdensity!!`, or something along those lines. This is because:
1. Almost _all_ samplers will have a cached value of the logdensity (up-to some constant) of their target in their state.
2. Some samplers will make use of said cached value, e.g. AdvancedMH uses this in its accept/reject computation.

Of course, this can be dealt with on a case-by-case basis by simply defining `updatestate!!` explicitly, _but_ this will be unnecessary in _most_ cases if we have something along the lines of `logdensity` and `setlogdensity!!`.

2021-11-19 02:16 UTC, torfjelde commented
Also, @devmotion you mentioned tests. Do you have anything particular in mind?

I have a test for the `MixtureSampler` outlined in the docs using AdvancedMH.jl, but that seems a bit "too heavy". At the same time, doing something like:
```julia
struct TestState
    params
    logp
end

setvalues!!(s::TestState) = ...
```
etc. seems quite useless :shrug: 

We could potentially take the test I have for the `MixtureSampler` and add a super-simple implementation of `RWMH` to the test-suite of AbstractMCMC? Not sure I'm too big a fan of this either though, as it'll be more like an example use-case rather than testing the functionality provided by `updatestate!!` etc.

2021-12-04 21:46 UTC, torfjelde commented
> On additional thing we might want to consider adding: `logdensity` and `setlogdensity!!`, or something along those lines. This is because:
> 
> 1. Almost _all_ samplers will have a cached value of the logdensity (up-to some constant) of their target in their state.
> 2. Some samplers will make use of said cached value, e.g. AdvancedMH uses this in its accept/reject computation.
> 
> Of course, this can be dealt with on a case-by-case basis by simply defining `updatestate!!` explicitly, _but_ this will be unnecessary in _most_ cases if we have something along the lines of `logdensity` and `setlogdensity!!`.
> 
> What do you say @devmotion @cpfiffer ? Add or not add, that is the question.

Yo boys @devmotion @cpfiffer! You got any thoughts on the above? AFAIK this is the only thing that's holding this PR back.

2021-12-04 22:24 UTC, devmotion commented on src/AbstractMCMC.jl
> +Base.values
Do we really want to use `Base.values` here? I think adding this documentation should be considered type piracy and would only be allowed if we define it only for our own types as arguments (which we can't do here).

Unrelated, why did you use `@doc`?

2021-12-05 22:06 UTC, cpfiffer commented
> Yo boys @devmotion @cpfiffer! You got any thoughts on the above? AFAIK this is the only thing that's holding this PR back.

Woops, sorry, missed this one. Full support from me on this one!

2021-12-05 22:54 UTC, devmotion commented
Ah I also missed this question. I think it would probably be useful but I would leave it for a separate PR. There were quite many discussions about `logdensity` functions recently and there was a push for unifying them throughout the Julia ecosystem. DensityInterface.jl defines a common interface for log density functions and their evaluations now that is used by e.g. Distributions, AbstractPPL, and (AFAIK) in the future also MeasureTheory. Hence IMO we should be a bit careful and not introduce a different `logdensity` function here, now that we unified them, but also make sure that it corresponds to the DensityInterface assumptions (if we use its interface).

2021-12-05 23:29 UTC, torfjelde commented on src/AbstractMCMC.jl
> +Base.values
> Do we really want to use Base.values here? I think adding this documentation should be considered type piracy and would only be allowed if we define it only for our own types as arguments (which we can't do here).

Hmm, I do agree with this. I'm coming around to `values` not being the best idea.

> Unrelated, why did you use @doc?

IIRC you need `@doc` here to be able to add the docstring? I.e. if you remove the `@doc` it won't be added to the docstring of `Base.values`.

2021-12-05 23:30 UTC, torfjelde commented
Yeah I was actually looking at the newly introduced `logdensity` stuff today, so I agree that maybe this should be done in a separate PR :+1:

2021-12-07 01:56 UTC, torfjelde commented
I renamed `values` and `setvalues!!` to `realize` and `realize!!` as mentioned earlier.

Even if we're not completely happy with these names, we can instead just change these at a later stage.

2021-12-07 02:06 UTC, torfjelde commented
> Ah I also missed this question. I think it would probably be useful but I would leave it for a separate PR. There were quite many discussions about logdensity functions recently and there was a push for unifying them throughout the Julia ecosystem. DensityInterface.jl defines a common interface for log density functions and their evaluations now that is used by e.g. Distributions, AbstractPPL, and (AFAIK) in the future also MeasureTheory. Hence IMO we should be a bit careful and not introduce a different logdensity function here, now that we unified them, but also make sure that it corresponds to the DensityInterface assumptions (if we use its interface).

After looking into DensityInterface.jl I don't think there's anything that should be relevant for AbstractMCMC's functionality for setting and extracting log-probabilities _from states/transitions_. For the `AbstractModel`, etc., then it's def relevant though!

So maybe we should just introduce `logprob` or `logtargetprob` or maybe even just `logtarget`, and its corresponding `set..!!`? I'm realizing more and more that it's necessary to be able to transfer the log target-prob to the next state if we want to do something interesting. In fact, I think `update!!` state should optionally be able to take the `AbstractModel` that we're sampling from too so that it can re-evaluate the current state if need be.

2024-10-10 07:36 UTC, sunxd3 requested changes
Let's make a final push to get this merged!

Apologize for the amount of comments. My proposal here is, in spirit, the same as what the PR already has. The differences are:

1. not defining `updatestates!!`: sampler packages can define there own internal functions
2. renaming `realize` and `realize!!` to `getparams` and `setparams!!`: there are no perfect names here, these are the names we are currently using in `Turing.jl`, they are   self-explanatory enough
3. no longer taking `model` as argument, also force returning and receiving `Vector`: this makes the proposed interface less flexible, but I think they are sufficient, when needs arise, we can always add version with `model` arguements

2024-10-10 07:36 UTC, sunxd3 commented on src/AbstractMCMC.jl
> +
```suggestion

"""
    getparams(state[; kwargs...])

Retrieve the values of parameters from the sampler's `state` as a `Vector{<:Real}`.
"""
function getparams end

"""
    setparams!!(state, params)

Set the values of parameters in the sampler's `state` from a `Vector{<:Real}`. This function should
follow the `BangBang` interface: mutate `state` in-place if possible and return the
mutated `state`. Otherwise, it should return a new `state` containing the updated parameters.

Although not enforced, it should hold that `setparams!!(state, getparams(state)) == state`. In another
word, the sampler should implement a consistent transformation between its internal representation
and the vector representation of the parameter values.
"""
function setparams!! end
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +AbstractMCMC.realize!!
```suggestion
AbstractMCMC.getparams
AbstractMCMC.setparams!!
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +```
```suggestion
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +- `weights`: collection of weights representing the probability of chosing the corresponding sampler.
```suggestion
- `weights`: collection of weights representing the probability of choosing the corresponding sampler.
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +For (2) the reason is similar: some samplers might keep track of the variables _in the state_ differently, e.g. you might have a sampler which is _independent_ of the current realizations and the sta
```suggestion
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +[`AbstractMCMC.updatestate!!`](@ref) comes into play in defining/computing ``\mathcal{K}_i(\cdot \mid X_{t - 1})`` since ``X_{t - 1}`` could be coming from a different sampler.
```suggestion
[`AbstractMCMC.getparams`](@ref) and [`AbstractMCMC.setparams!!`](@ref) comes into play in defining/computing ``\mathcal{K}_i(\cdot \mid X_{t - 1})`` since ``X_{t - 1}`` could be coming from a different sampler.
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +)
```suggestion
state_current = AbstractMCMC.setparams!!(
    state.states[i], 
    AbstractMCMC.getparams(state.states[i_prev]),
)
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +- `transition`: the transition resulting from this `step`.
```suggestion
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +The reason for (1) is that lots of samplers keep track of more than just the previous realizations of the variables, e.g. in `AdvancedHMC.jl` we keep track of the momentum used, the metric used, etc.
```suggestion
We need to keep track of the states of _all_ components rather than just the state for the sampler we used previously.
The reason is that lots of samplers keep track of more than just the previous realizations of the variables, e.g. in `AdvancedHMC.jl` we keep track of the momentum used, the metric used, etc.
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +Hence, we need the `transition`, which should always contain the realizations, to make sure we can resume from the same point in the space in the next `step`.
```suggestion
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +    transition::T
```suggestion
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +struct MixtureState{T,S}
```suggestion
struct MixtureState{S}
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +    )
```suggestion
    state_current = AbstractMCMC.setparams!!(  
        state.states[i], 
        AbstractMCMC.getparams(state.states[i_prev]),  
    )
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +    state_new = MixtureState(i, transition, states_new)
```suggestion
    state_new = MixtureState(i, states_new)
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +    state = MixtureState(i, transition, states)
```suggestion
    state = MixtureState(i, states)
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +Suppose we then wanted to use this with some of the packages which implements AbstractMCMC.jl's interface, e.g. [`AdvancedMH.jl`](https://github.com/TuringLang/AdvancedMH.jl), then we'd simply have t
```suggestion
Suppose we then wanted to use this with some of the packages which implements AbstractMCMC.jl's interface, e.g. [`AdvancedMH.jl`](https://github.com/TuringLang/AdvancedMH.jl), then we'd simply have to implement `getparams` and `setparams!!`.
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +```
```suggestion
```

2024-10-10 07:36 UTC, sunxd3 commented on docs/src/api.md
> +This issue should eventually disappear as the community moves towards a unified approach to implement `AbstractMCMC.AbstractModel`.
```suggestion
```

2024-10-10 13:23 UTC, torfjelde commented on docs/src/api.md
> +For (2) the reason is similar: some samplers might keep track of the variables _in the state_ differently, e.g. you might have a sampler which is _independent_ of the current realizations and the sta
Why are we removing this?

2024-10-10 14:25 UTC, sunxd3 commented on docs/src/api.md
> +For (2) the reason is similar: some samplers might keep track of the variables _in the state_ differently, e.g. you might have a sampler which is _independent_ of the current realizations and the sta
My bad, I prepared to write some explanation but forgot. 

The deleted part was to explain 
```
2. We need to put the `transition` from the `step` into the state.
```

because the `transition` is no longer needed (we effectively force samplers to store params in state), I felt we don't need this line anymore

2024-10-10 19:56 UTC, torfjelde commented on docs/src/api.md
> +For (2) the reason is similar: some samplers might keep track of the variables _in the state_ differently, e.g. you might have a sampler which is _independent_ of the current realizations and the sta
Ah gotcha :+1: Thanks @sunxd3 !

2024-10-11 03:03 UTC, sunxd3 commented
@hong @devmotion can you give a quick look?
If no objections, I may merge this by the end of today (Oct 11).

2024-10-12 09:14 UTC, sunxd3 commented
minor version bumped for added feature, merging now.

2024-10-12 09:14 UTC, merged